language: go

go:
  - 1.8

sudo: required

services: 
  - docker

before_install:
  - docker pull ryankurte/docker-native-dev

install:
  - docker run --rm -it -v`pwd`:/root ryankurte/docker-native-dev /bin/bash -c "make install && make"

script:
  - docker run --rm -it -v`pwd`:/root ryankurte/docker-native-dev /bin/bash -c "make test"

notifications:
  email: false
