language: go

go:
  - 1.8

sudo: required

services: 
  - docker

before_install:
  - docker pull ryankurte/docker-native-dev

install:
  - docker run --rm -it -v`pwd`:/root/go/src/github.com/ryankurte/ons ryankurte/docker-native-dev /bin/bash -c "cd /root/go/src/github.com/ryankurte/ons && make install && make"

script:
  - docker run --rm -it -v`pwd`:/root/go/src/github.com/ryankurte/ons ryankurte/docker-native-dev /bin/bash -c "cd /root/go/src/github.com/ryankurte/ons && make test"

notifications:
  email: false
